---
title: "patient-share"
author: "Batta Liu"
date: "September 15, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require("RPostgreSQL")
library(plyr)
library(dplyr)
library("ggplot2")
library(ggmap)
```

```{r Connection, echo=FALSE}
# create a connection
# save the password that we can "hide" it as best as we can by collapsing it
pw <- {
	"no323232"
}

# loads the PostgreSQL driver
drv <- dbDriver("PostgreSQL")

# creates a connection to the postgres database
# note that "con" will be used later in each connection to the database
con <- dbConnect(drv, dbname = "liubatta",
								 host = "192.168.0.10", port = 5432,
								 user = "liubatta", password = pw)

rm(pw) # removes the password

# check for the cartable
dbExistsTable(con, "tmp_test")

```

```{r}
# import the shared patient data
df.patient.share.14 <- dbGetQuery(con, 
 												" SELECT npi1, npi2, pair_count,
bene_count,same_day_count,
 											entity_type_code,  
											provider_business_practice_location_address_city_name,	provider_business_practice_location_address_state_name, 													provider_business_practice_location_address_postal_code,
 													healthcare_provider_taxonomy_code_1
 													from patient_share_2014_180_ca1")
df.patient.share.14$npi1 <- as.numeric(df.patient.share.14$npi1)
df.patient.share.14$npi2 <- as.numeric(df.patient.share.14$npi2)


df.patient.share.13 <- dbGetQuery(con, 
																	" SELECT npi1, npi2, pair_count, bene_count,same_day_count,
																	entity_type_code,
provider_business_practice_location_address_city_name,
provider_business_practice_location_address_state_name,
									provider_business_practice_location_address_postal_code,
																	healthcare_provider_taxonomy_code_1
																	from patient_share_2013_180_ca1")
df.patient.share.13$npi1 <- as.numeric(df.patient.share.13$npi1)
df.patient.share.13$npi2 <- as.numeric(df.patient.share.13$npi2)

df.npi.geocode <- dbGetQuery(con, 
																	" SELECT
                npi_id,entity_type_code,
                ctc,
								healthcare_provider_taxonomy_code_1,lon,lat
								from npi_16ca_15geocode_visualization")

```
Combine patient sharing data with geocode data. I try to plot all the locations and paths, but the max url lenth is 2048 in function get_googlemap(). Therefore, I pick city "NAPA" and npi1s with # of links <=30 to plot the networks.

First of all, I need to make up data frames for plots and list of data frames for paths.
Then I can use get_googlemap to get the map and ggmap it.
```{r}
reserve <- df.patient.share.13
df.patient.share.13 <- reserve[which(reserve$provider_business_practice_location_address_city_name=="NAPA"),]
reserve14 <- df.patient.share.14
df.patient.share.14 <- reserve14[which(reserve14$provider_business_practice_location_address_city_name=="NAPA"),]
df.patient.share.13$npi1npi2 <- paste(df.patient.share.13$npi1,df.patient.share.13$npi2,sep = "")
df.patient.share.14$npi1npi2 <- paste(df.patient.share.14$npi1,df.patient.share.14$npi2,sep = "")
disappear1314 <- anti_join(df.patient.share.13,df.patient.share.14,by = "npi1npi2")
stay1314 <- inner_join(df.patient.share.13,df.patient.share.14,by = "npi1npi2")
new1314 <- anti_join(df.patient.share.14,df.patient.share.13,by = "npi1npi2")

only.geocode <- df.npi.geocode %>% 
	select(npi_id, lon, lat,ctc)
only.geocode <- only.geocode[which(only.geocode$ctc==1),]
only.geocode$ctc <- NULL
stay1314.geo <- inner_join(stay1314, only.geocode, by = c("npi1.x"="npi_id"))
stay1314.geo <- inner_join(stay1314.geo, only.geocode, by = c("npi2.x"="npi_id"))

tmp <- stay1314.geo %>% 
	group_by(lon.x, lat.x) %>% 
	tally()


tmp2 <- stay1314.geo %>% 
	group_by(lon.x, lat.x,lon.y, lat.y) %>% 
	tally
tmp3 <- tmp2 %>% 
	group_by(lon.x, lat.x) %>% 
	tally
tmp3[which(tmp3$n<=30 & tmp3$n>=29),]
tmp2$n <- NULL
tmp2 <- data.frame(tmp2)
tmp.2 <- tmp2 %>% 
	select(lon.x,lat.x) %>% 
	filter(lon.x == -122.29, lat.x ==38.29)
names(tmp.2) <- c("lon","lat")
tmp.3 <- tmp2 %>% 
	filter(lon.x == -122.29, lat.x ==38.29) %>% 
	select(lon.y, lat.y)
names(tmp.3) <- c("lon","lat")

tmp2.list <- split(tmp.2, seq(nrow(tmp.2)))
tmp3.list <- split(tmp.3, seq(nrow(tmp.3)))
system.time(tmp4 <- mapply(rbind, tmp2.list, tmp3.list, SIMPLIFY=FALSE))

tmp4 <- tmp4 %>% 
	group_by(lon)
map1 <- get_googlemap("NAPA", markers = tmp, path = tmp4,scale = 2) 
ggmap(map1)
map2 <- get_googlemap("NAPA", markers = tmp, path = tmp4[31:60],scale = 2) 
ggmap(map2)
map3 <- get_googlemap("NAPA", markers = tmp, path = tmp4[61:90],scale = 2) 
ggmap(map3)
map4 <- get_googlemap("NAPA", markers = tmp, path = tmp4[91:120],scale = 2) 
ggmap(map4)

map5 <- get_googlemap("NAPA", markers = tmp, path = tmp4[121:150],scale = 2) 
ggmap(map5)


```


```{r}
tmp.2 <- tmp2 %>% 
	select(lon.x,lat.x) 
names(tmp.2) <- c("lon","lat")
tmp.3 <- tmp2 %>% 
	select(lon.y, lat.y)
names(tmp.3) <- c("lon","lat")

tmp2.list <- split(tmp.2, seq(nrow(tmp.2)))
tmp3.list <- split(tmp.3, seq(nrow(tmp.3)))
system.time(tmp4 <- mapply(rbind, tmp2.list, tmp3.list, SIMPLIFY=FALSE))

tmp4 <- tmp4 %>% 
	group_by(lon)
map1 <- get_googlemap("NAPA", zoom = 10) 
mapPoints <- ggmap(map1)+geom_point(aes(x = lon.x, y = lat.x,size = sqrt(n)), data = tmp, alpha = .5)
```

